services:
  auth-db:
    image: mysql:8.0
    container_name: chatapp_auth_db
    environment:
      - MYSQL_DATABASE=${AUTH_DB_NAME:-chatapp_auth_service} # use environment variable or default to 'chatapp_auth_service'
      - MYSQL_USER=${AUTH_DB_USER:-chatapp_auth_user}
      - MYSQL_PASSWORD=${AUTH_DB_PASSWORD:-chatapp_auth_password}
      - MYSQL_ROOT_PASSWORD=${AUTH_DB_ROOT_PASSWORD:-chatapp_rootpassword} 
    ports:
      - "${AUTH_DB_PORT:-3306}:3306"
    volumes:
      - auth_db_data:/var/lib/mysql
    networks:
      - chatapp_network

volumes:
  auth_db_data:

# Define the custom network for the chat application services
# This network allows the services to communicate with each other using their service names as hostnames.
# The 'bridge' driver is used for simplicity, but you can choose other drivers based on your needs (e.g., overlay for swarm mode).
networks:
  chatapp_network:
    driver: bridge